### ISSUE TITLE
MultiStreamRecoder : Changing resolution doesn't work

### ISSUE THREAD

**Issue by Param-Harrison** [streamproc/MediaStreamRecorder#27]
Setting a different resolution e.g. 640x480 still produces a 320x240 webm video in MultiStreamRecorder.  Let us know, if we need to change any mediacontraints?

**Comment by muaz-khan** [comment]
[Latest updates](https://github.com/streamproc/MediaStreamRecorder/commit/fb834d216b42766bf03e7201f50ecda3fa434f3f) includes webm recording which is having following media information:

**Type:** Video
**Codec:** Google/On2's VP8 Video (VP80)
**Resolutions:** 1280x720
**Decoded Format:** Planar 4:20:0 YUV

Demo:

* https://www.webrtc-experiment.com/msr/MultiStreamRecorder.html

You can set resolutions in 3-4 ways. E.g.

```javascript
yourVideoElement.width = 1280;
yourVideoElement.height = 720;
multiStreamRecorder.video = yourVideoElement;

// or
multiStreamRecorder.width = 1280;
multiStreamRecorder.heigth = 720;

// or
multiStreamRecorder.video = {
    width: 1280,
    height: 720
};
multiStreamRecorder.canvas = {   // resolutions here
    width: 1280,
    height: 720
};
```

Audio (WAV) metadata information:

**Type:** Audio
**Codec:** PCM S16 LE (s161)
**Channels:** Stereo
**Sample rate:** 44100 Hz
**Bits per sample:** 16

Also, regarding [#26](https://github.com/streamproc/MediaStreamRecorder/issues/26), in latest updates, there is just 200-300 milliseconds difference. Previously it was one and half seconds gap, because HTMLVideoElement was created on the fly, and it took time to render/play it.

I'm passing HTMLVideoElement like this snippet:

```javascript
multiStreamRecorder.video = htmlVideoElement;

multiStreamRecorder.addEventListener('loadedmetadata', function() {
    multiStreamRecorder.start(3* 1000);
}, false);
```

**Comment by Param-Harrison** [comment]
Thanks @muaz-khan. Thanks for your time. I will check it out.

**Comment by Param-Harrison** [comment]
This resolution bug is resolved. But the audio blob isn't working. Even in your demo page. I will open it as new bug so that It will be easy to track...
