### ISSUE TITLE
Each audio chunk first second corrupt

### ISSUE THREAD

**Issue by lazyexpert** [streamproc/MediaStreamRecorder#57]
Hi. I am using (currently only audio) your library for recording purposes.
I'm writing 60 second chunks and send them to server, where I merge them.
All work fine. But one moment: almost each chunk's first second is broken. It sounds like repeated sound with high frequency... I hear it on the very first chunks I recieve from frontend, so that's why asking for your help. 

I've tried switching audio formats, but that doesn't help( tried 'wav,ogg' ).

Also I have option for writing video(with audio) same problem with audio there, but video file looks straight.

Any suggestions? 
Forgot to mention, that I'm using simple constraints while { audio : "true" }.

I've experimented a little with duration. Looks like with less duration comes less noise. And this noise happens even on first chunk, at start.

**Comment by abhisirohi72** [comment]
can you send me your chunk code?

**Comment by Rsgm** [comment]
This may fix your corrupted audio.

https://github.com/muaz-khan/RecordRTC/issues/48

**Comment by fabripeco** [comment]
Hi, here I have the same problem recording video and audio in chrome as separate blobs and setting the interval to 5s (like in the demo). Randomly the audio data is corrupted by high frequency noise in the first part (the same in the demo https://www.webrtc-experiment.com/msr/MultiStreamRecorder.html ). I have also simple constraints on the getUserMedia, I'm acquiring only mono channel with a bufferSize of 4096B. 

Then I set an higher bufferSize (8192) and the problem seems to be disappeared. Can it be a possibile solution? Any idea about this?

Thank you very much

**Comment by lazyexpert** [comment]
As far as I'm no longer working under that project I'll close this issue. There's almost identical one you may continue discussion there. Good luck =)
